ALTER TABLE employees
    ADD COLUMN salary DECIMAL(10, 2) NULL AFTER role,
    ADD COLUMN admission_date DATE NULL AFTER salary,
    ADD COLUMN deactivation_date DATE NULL AFTER admission_date;

UPDATE employees
SET department = CASE
    WHEN department IN ('ADMINISTRAÇÃO', 'ADMINISTRACAO') THEN 'ADMINISTRACAO'
    WHEN department = 'COMERCIAL' THEN 'COMERCIAL'
    WHEN department = 'COMPRAS' THEN 'COMPRAS'
    WHEN department = 'CONTABILIDADE' THEN 'CONTABILIDADE'
    WHEN department IN ('DEPARTAMENTO PESSOAL', 'DEPARTAMENTO_PESSOAL') THEN 'DEPARTAMENTO_PESSOAL'
    WHEN department = 'FINANCEIRO' THEN 'FINANCEIRO'
    WHEN department IN ('JURÍDICO', 'JURIDICO') THEN 'JURIDICO'
    WHEN department IN ('LOGÍSTICA', 'LOGISTICA') THEN 'LOGISTICA'
    WHEN department = 'MARKETING' THEN 'MARKETING'
    WHEN department IN ('OPERAÇÕES', 'OPERACOES') THEN 'OPERACOES'
    WHEN department IN ('PLANEJAMENTO ESTRATÉGICO', 'PLANEJAMENTO ESTRATEGICO', 'PLANEJAMENTO_ESTRATEGICO') THEN 'PLANEJAMENTO_ESTRATEGICO'
    WHEN department IN ('RECURSOS HUMANOS', 'RECURSOS_HUMANOS') THEN 'RECURSOS_HUMANOS'
    WHEN department IN ('RELAÇÕES PÚBLICAS', 'RELACOES PUBLICAS', 'RELACOES_PUBLICAS') THEN 'RELACOES_PUBLICAS'
    WHEN department IN ('TECNOLOGIA DA INFORMAÇÃO', 'TECNOLOGIA DA INFORMACAO', 'TECNOLOGIA_DA_INFORMACAO') THEN 'TECNOLOGIA_DA_INFORMACAO'
    WHEN department = 'VENDAS' THEN 'VENDAS'
    ELSE 'RECURSOS_HUMANOS'
END;
